### PR TITLE
add redirects file

### PR DESCRIPTION
**Pull request by kamila-wilczynska**
added _redirects file
image

### CODE REVIEW

**Comment by orangespaceman** [comment]
Note that this is an attempt to fix the following issue: when you load the app (https://chaos-animals.netlify.app/), navigate to the product page (https://chaos-animals.netlify.app/product) and then reload the page, the server currently returns a 404 error because that URL doesn't map to a real file...

**Review by orangespaceman — APPROVED** [review]
Let's hope this works 🤞

**Review by Sebbybobbler — APPROVED** [review]

**Review by NicoClack — CHANGES_REQUESTED** [review]
Your branch is behind master so it doesn't have the Vite config fix. @orangespaceman is a rebase the solution?

**Comment by NicoClack** [comment]
Or the merge might fix it actually

**Review by NicoClack — APPROVED** [review]
Worth a shot actually

**Comment by orangespaceman** [comment]
@hedgehog125 The PR will merge this change into the latest `master` so it should be fine (although it is good practice to always work from the latest commit, just in case...)

**Comment by orangespaceman** [comment]
It works! 🙂

**Comment by NicoClack** [comment]
@orangespaceman In a professional setting would we have rebased since the tests were failing?

**Comment by orangespaceman** [comment]
@hedgehog125 yes, it would have been a good idea to do so just so we could ensure everything worked as expected prior to merging. It would also have let us deploy the branch to Netlify so we could test the branch in a browser

**Pull request merged**
